language: go

go:
  - 1.5
  - 1.6
  - 1.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev

install:
  - go get -t -v ./...

script: 
  - GOOS=linux GOARCH=arm GOARM=7 go get -u github.com/gogits/gogs

notifications:
  email:
    - vinothsubramanian@gmail.com
  slack: gophercn:o5pSanyTeNhnfYc3QnG0X7Wx
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b590f8e03882f7aedc3e
    on_success: never 
    on_failure: never 
    on_start: never     
